<?php
/**
 * Mobtexting SMS Notifications
 *
 * Sends transactional SMS notifications
 *
 */

/** @var \Magento\Framework\View\Element\Html\Link\Current $block */
?>
<li class="nav item<?= $block->isCurrent() || $block->getIsHighlighted() ? ' current' : '' ?>" id="sms-notifications-manage-link">
    <?php if (!$block->isCurrent()): ?>
    <a href="<?= $block->escapeHtml($block->getHref()) ?>"<?= $block->getTitle() ? ' title="' . $block->escapeHtmlAttr(__($block->getTitle())) . '"' : '' ?>>
    <?php endif ?>
    <?php if ($block->isCurrent() || $block->getIsHighlighted()): ?>
        <strong>
    <?php endif ?>
        <?= $block->escapeHtml(__($block->getLabel())) ?>
    <?php if ($block->isCurrent() || $block->getIsHighlighted()): ?>
        </strong>
    <?php endif ?>
    <?php if (!$block->isCurrent()): ?>
    </a>
    <?php endif ?>
</li>
